language: objective-c
osx_image: xcode7.3
script:
  - make
before_install:
  - curl -O https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-osx.pkg
  - sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-osx.pkg -target /
  - export PATH=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a.xctoolchain/usr/bin:"${PATH}"
notifications:
  email: false
